#!/usr/bin/env Rscript
# -----------------------------------------------------------------------------
# plot_filter_impact.R
#
# Read the log file produced by count_filters.sh and generate plots that show
# how each filtering level changes the number of retained variants.
# -----------------------------------------------------------------------------
suppressPackageStartupMessages({
  library(ggplot2)
  library(data.table)
})

args <- commandArgs(trailingOnly = TRUE)

# The first argument is the mandatory log file.
# The second argument is optional and defines the output directory.
if (length(args) < 1) {
  cat("Usage: Rscript plot_filter_impact.R <count_filters.txt> [output_directory]\n")
  cat("  The log file produced by count_filters.sh is required.\n")
  quit(status = 1)
}

logfile <- args[1]
outdir <- ifelse(length(args) >= 2, args[2], "results/plots")

if (!file.exists(logfile)) {
  cat(sprintf("ERROR: File '%s' not found\n", logfile))
  quit(status = 1)
}

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

# -----------------------------------------------------------------------------
# Read and parse the log file produced by count_filters.sh
# -----------------------------------------------------------------------------
parse_log <- function(logfile) {
  lines <- readLines(logfile, warn = FALSE)

  # Data lines start with names like P25/... or P27/...
  data_lines <- grep("^P[0-9]+/", lines, value = TRUE)

  if (length(data_lines) == 0) {
    cat("ERROR: No data lines found in the log file.\n")
    cat("Check that the file was generated by count_filters.sh\n")
    quit(status = 1)
  }

  results <- list()
  for (line in data_lines) {
    # The log uses multiple spaces as separators.
    parts <- trimws(strsplit(line, "\\s{2,}")[[1]])
    if (length(parts) >= 6) {
      sample_name <- parts[1]
      passage <- sub("/.*", "", sample_name)

      # Convert commas to dots before converting to numeric values.
      clean_num <- function(x) as.numeric(gsub(",", ".", trimws(x)))

      results[[length(results) + 1]] <- data.table(
        sample = sample_name,
        passage = passage,
        none = clean_num(parts[2]),
        base = clean_num(parts[3]),
        moderate = clean_num(parts[4]),
        strict = clean_num(parts[5]),
        dp_median = clean_num(parts[6])
      )
    }
  }

  if (length(results) == 0) {
    cat("ERROR: Unable to parse data from the log file.\n")
    quit(status = 1)
  }
  rbindlist(results)
}

cat("Reading log file:", logfile, "\n")
dt <- parse_log(logfile)
cat(sprintf("Data loaded: %d samples, %d passages\n", nrow(dt), length(unique(dt$passage))))

# -----------------------------------------------------------------------------
# Compute means per passage
# -----------------------------------------------------------------------------
avg_dt <- dt[, .(
  `Without filter` = round(mean(none)),
  Base = round(mean(base)),
  Moderate = round(mean(moderate)),
  Strict = round(mean(strict)),
  dp_median_mean = round(mean(dp_median)),
  n = .N
), by = passage]

# Keep passages in natural numeric order (P25, P26, P27, etc.).
passage_order <- unique(dt$passage)
passage_order <- passage_order[order(as.numeric(gsub("\\D", "", passage_order)))]
avg_dt[, passage := factor(passage, levels = passage_order)]

# Convert to long format for ggplot.
long_dt <- melt(
  avg_dt,
  id.vars = c("passage", "dp_median_mean", "n"),
  measure.vars = c("Without filter", "Base", "Moderate", "Strict"),
  variable.name = "filter",
  value.name = "variants"
)

long_dt[, filter := factor(filter, levels = c("Without filter", "Base", "Moderate", "Strict"))]

# Define a stable color palette.
filter_colors <- c(
  "Without filter" = "#85B7EB",
  "Base"           = "#97C459",
  "Moderate"       = "#EF9F27",
  "Strict"         = "#E24B4A"
)

# -----------------------------------------------------------------------------
# PLOT 1: Mean variant count per passage and filter level
# -----------------------------------------------------------------------------
p1 <- ggplot(long_dt, aes(x = passage, y = variants, fill = filter)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7) +
  geom_text(
    aes(label = variants),
    position = position_dodge(width = 0.8),
    vjust = -0.5,
    size = 2.8,
    color = "grey30"
  ) +
  scale_fill_manual(values = filter_colors, name = "Filter") +
  labs(
    title = "Mean number of variants per passage and filtering level",
    subtitle = sprintf("%d samples in total — data from count_filters.sh", nrow(dt)),
    x = "Passage",
    y = "Number of variants (mean)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "grey50", size = 11),
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, max(long_dt$variants) * 1.12))

ggsave(file.path(outdir, "filter_impact_means.png"), p1, width = 12, height = 7, dpi = 300)
cat("Saved:", file.path(outdir, "filter_impact_means.png"), "\n")

# -----------------------------------------------------------------------------
# PLOT 2: Boxplots showing dispersion between samples
# -----------------------------------------------------------------------------
long_all <- melt(
  dt,
  id.vars = c("sample", "passage", "dp_median"),
  measure.vars = c("none", "base", "moderate", "strict"),
  variable.name = "filter",
  value.name = "variants"
)

long_all[, filter := factor(
  filter,
  levels = c("none", "base", "moderate", "strict"),
  labels = c("Without filter", "Base", "Moderate", "Strict")
)]
long_all[, passage := factor(passage, levels = passage_order)]

p2 <- ggplot(long_all, aes(x = passage, y = variants, fill = filter)) +
  geom_boxplot(
    position = position_dodge(width = 0.8),
    width = 0.65,
    outlier.size = 1.5,
    outlier.alpha = 0.6
  ) +
  scale_fill_manual(values = filter_colors, name = "Filter") +
  labs(
    title = "Distribution of variants by passage and filter level",
    subtitle = "Boxplots show between-sample variability within each passage",
    x = "Passage",
    y = "Number of variants"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "grey50", size = 11),
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  )

ggsave(file.path(outdir, "filter_impact_boxplot.png"), p2, width = 12, height = 7, dpi = 300)
cat("Saved:", file.path(outdir, "filter_impact_boxplot.png"), "\n")

# -----------------------------------------------------------------------------
# PLOT 3: Retention percentage relative to the unfiltered set
# -----------------------------------------------------------------------------
retention_dt <- copy(long_dt)
none_vals <- avg_dt[, .(passage, total = `Without filter`)]
retention_dt <- merge(retention_dt, none_vals, by = "passage")
retention_dt[, pct := round(100 * variants / total, 1)]
retention_dt <- retention_dt[filter != "Without filter"]

p3 <- ggplot(retention_dt, aes(x = passage, y = pct, fill = filter)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7), width = 0.6) +
  geom_text(
    aes(label = paste0(pct, "%")),
    position = position_dodge(width = 0.7),
    vjust = -0.5,
    size = 3,
    color = "grey30"
  ) +
  scale_fill_manual(values = filter_colors[c("Base", "Moderate", "Strict")], name = "Filter") +
  geom_hline(yintercept = 50, linetype = "dashed", color = "grey60", linewidth = 0.4) +
  annotate("text", x = 0.5, y = 52, label = "50%", size = 3, color = "grey50", hjust = 0) +
  labs(
    title = "Variant retention by filter level (vs unfiltered)",
    subtitle = "Percentage of variants kept after each filtering level",
    x = "Passage",
    y = "Retention (%)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "grey50", size = 11),
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 110))

ggsave(file.path(outdir, "filter_retention_pct.png"), p3, width = 12, height = 7, dpi = 300)
cat("Saved:", file.path(outdir, "filter_retention_pct.png"), "\n")

# -----------------------------------------------------------------------------
# PLOT 4: Median DP per sample, to identify low-depth problematic samples
# -----------------------------------------------------------------------------
dt[, passage := factor(passage, levels = passage_order)]
dt[, low_dp := dp_median < 100]

p4 <- ggplot(dt, aes(x = passage, y = dp_median)) +
  geom_jitter(aes(color = low_dp), width = 0.2, size = 2.5, alpha = 0.7) +
  geom_boxplot(alpha = 0.3, outlier.shape = NA, width = 0.5) +
  scale_color_manual(
    values = c("FALSE" = "#378ADD", "TRUE" = "#E24B4A"),
    labels = c("DP >= 100", "DP < 100"),
    name = ""
  ) +
  scale_y_log10(labels = scales::comma_format()) +
  labs(
    title = "Median depth (DP) per sample",
    subtitle = "Logarithmic scale — red points are low-depth samples",
    x = "Passage",
    y = "Median DP (log10)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "grey50", size = 11),
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  )

ggsave(file.path(outdir, "dp_median_per_sample.png"), p4, width = 10, height = 7, dpi = 300)
cat("Saved:", file.path(outdir, "dp_median_per_sample.png"), "\n")

# -----------------------------------------------------------------------------
# Final text summary printed to the console
# -----------------------------------------------------------------------------
cat("\n=== SUMMARY ===\n")
cat(sprintf("4 figures generated in %s/\n", outdir))
cat("  - filter_impact_means.png   : mean barplot\n")
cat("  - filter_impact_boxplot.png : dispersion boxplot\n")
cat("  - filter_retention_pct.png  : retention percentages\n")
cat("  - dp_median_per_sample.png  : depth per sample\n")

low_dp_samples <- dt[dp_median < 100]
if (nrow(low_dp_samples) > 0) {
  cat("\nLow-depth samples (median DP < 100):\n")
  for (i in 1:nrow(low_dp_samples)) {
    cat(sprintf("  - %s (median DP = %.0f)\n", low_dp_samples$sample[i], low_dp_samples$dp_median[i]))
  }
}
